version: '2'
services:

  redis-sentinel:
    image: uonappdev.azurecr.io/cache/redis-sentinel:dev
    environment:
      SENTINEL_DOWN_AFTER_MILLISECONDS: '5000'
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=redis-sentinel
      io.rancher.container.create_agent: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

  redis-server:
    image: uonappdev.azurecr.io/cache/redis-server:dev
    stdin_open: true
    volumes:
      - /data_nfs/cache-data:/data:rw
    tty: true
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=redis-server
      io.rancher.scheduler.affinity:host_label: uon.host.role=redis
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
